export const BLE_START = 'BLE_START';
export const BLE_SCAN_START = 'BLE_SCAN_START';
export const BLE_SCAN_ENDED = 'BLE_SCAN_ENDED';
export const BLE_CONNECT_ERROR = 'BLE_CONNECT_ERROR';
export const BLE_UPDATE_CONNECTED_PERIPHERALS = 'BLE_UPDATE_CONNECTED_PERIPHERALS';
export const BLE_UPDATE_AVAILABLE_PERIPHERALS = 'BLE_UPDATE_AVAILABLE_PERIPHERALS';
export const BLE_UPDATE_PERIPHERALS_WITH_SERVICES = 'BLE_UPDATE_PERIPHERALS_WITH_SERVICES';