export const BLE_START = 'BLE_START';
export const BLE_SCAN_START = 'BLE_SCAN_START';
export const BLE_SCAN_ENDED = 'BLE_SCAN_ENDED';

export const BLE_CONNECT_ERROR = 'BLE_CONNECT_ERROR';

export const BLE_UPDATE_CONNECTED_PERIPHERALS = 'BLE_UPDATE_CONNECTED_PERIPHERALS';
export const BLE_UPDATE_AVAILABLE_PERIPHERALS = 'BLE_UPDATE_AVAILABLE_PERIPHERALS';
export const BLE_UPDATE_KNOWN_PERIPHERALS = 'BLE_UPDATE_KNOWN_PERIPHERALS';

export const BLE_READ = 'BLE_READ';
export const BLE_READ_ERROR = 'BLE_READ_ERROR';
export const BLE_APPEND_READ_HISTORY = 'BLE_APPEND_READ_HISTORY';

export const BLE_NOTIFY = 'BLE_NOTIFY';
export const BLE_NOTIFY_STOP = 'BLE_NOTIFY_STOP';
export const BLE_NOTIFY_STARTED = 'BLE_NOTIFY_STARTED';
export const BLE_NOTIFY_STOPPED = 'BLE_NOTIFY_STOPPED';
export const BLE_NOTIFY_ERROR = 'BLE_NOTIFY_ERROR';

export const BLE_FAVORITE_ADD = 'BLE_FAVORITE_ADD';
export const BLE_FAVORITE_REMOVE = 'BLE_FAVORITE_REMOVE';

//

export const FILE_SAVE_PATH = '/unsent/';